version: '3'
services:
  postgres:
    image: postgres:15
    container_name: cse_warehouse
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: Kavindu2002
      POSTGRES_DB: cse_dwh
    ports:
      - "5433:5432"
    volumes:
      # Maps your local SQL folder to the container so we can run scripts easily
      - ./sql:/docker-entrypoint-initdb.d

      # NEW SERVICE: Airflow
  airflow:
    image: apache/airflow:2.7.1
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./data:/opt/airflow/data
    command: airflow standalone  # Runs webserver + scheduler in one container (Good for dev)
    ports:
      - "8080:8080"

      # 1. The Data Lake (S3 Compatible Storage)
  minio:
    image: minio/minio
    container_name: cse_datalake
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio_admin
      MINIO_ROOT_PASSWORD: minio_password
    command: server /data --console-address ":9001"
    volumes:
      - ./datalake_data:/data

  # 2. The Spark Master (The Brain)
  spark-master:
    image: apache/spark:3.5.0
    container_name: spark_master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "9090:8080"  # Spark Master Web UI
      - "7077:7077"  # Spark Master Port
    volumes:
      - ./data:/opt/spark/data

  # 3. The Spark Worker (The Muscle)
  spark-worker:
    image: apache/spark:3.5.0
    container_name: spark_worker
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      - SPARK_WORKER_WEBUI_PORT=8081
    volumes:
      - ./data:/opt/spark/data