version: '3'
services:
  postgres:
    image: postgres:15
    container_name: cse_warehouse
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: Kavindu2002
      POSTGRES_DB: cse_dwh
    ports:
      - "5433:5432"
    volumes:
      # Maps your local SQL folder to the container so we can run scripts easily
      - ./sql:/docker-entrypoint-initdb.d

      # NEW SERVICE: Airflow
  airflow:
    image: apache/airflow:2.7.1
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./data:/opt/airflow/data
    command: airflow standalone  # Runs webserver + scheduler in one container (Good for dev)
    ports:
      - "8080:8080"